"""added projections table

Revision ID: 7a2b8a59ae4f
Revises: e743e0017e0a
Create Date: 2019-07-05 20:59:40.437909

"""
from alembic import op
import sqlalchemy as sa

import goesbrowse.database


# revision identifiers, used by Alembic.
revision = '7a2b8a59ae4f'
down_revision = 'e743e0017e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('x_offset', sa.Integer(), nullable=True),
    sa.Column('y_offset', sa.Integer(), nullable=True),
    sa.Column('x_scale', sa.Integer(), nullable=True),
    sa.Column('y_scale', sa.Integer(), nullable=True),
    sa.Column('lon_0', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('file') as batch_op:
        batch_op.add_column(sa.Column('projection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('file_projection', 'projection', ['projection_id'], ['id'])
    # ### end Alembic commands ###

    # do data migration
    for file in goesbrowse.database.File.query.all():
        proj = goesbrowse.database.Projection.from_meta(file.json)
        if not proj:
            continue
        proj = proj.find_or_insert()
        file.projection = proj
    goesbrowse.database.sql.session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file') as batch_op:
        batch_op.drop_constraint('file_projection', type_='foreignkey')
        batch_op.drop_column('projection_id')
    op.drop_table('projection')
    # ### end Alembic commands ###
