"""initial revision

Revision ID: e743e0017e0a
Revises: 
Create Date: 2019-07-04 19:54:12.853630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e743e0017e0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jsonpath', sa.Text(), nullable=True),
    sa.Column('datapath', sa.Text(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_channel'), 'file', ['channel'], unique=False)
    op.create_index(op.f('ix_file_datapath'), 'file', ['datapath'], unique=True)
    op.create_index(op.f('ix_file_date'), 'file', ['date'], unique=False)
    op.create_index(op.f('ix_file_jsonpath'), 'file', ['jsonpath'], unique=True)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    op.create_index(op.f('ix_file_region'), 'file', ['region'], unique=False)
    op.create_index(op.f('ix_file_size'), 'file', ['size'], unique=False)
    op.create_index(op.f('ix_file_source'), 'file', ['source'], unique=False)
    op.create_index(op.f('ix_file_type'), 'file', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_type'), table_name='file')
    op.drop_index(op.f('ix_file_source'), table_name='file')
    op.drop_index(op.f('ix_file_size'), table_name='file')
    op.drop_index(op.f('ix_file_region'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_jsonpath'), table_name='file')
    op.drop_index(op.f('ix_file_date'), table_name='file')
    op.drop_index(op.f('ix_file_datapath'), table_name='file')
    op.drop_index(op.f('ix_file_channel'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
