"""swapped file and product names

Revision ID: eac00fc6a70d
Revises: c6aead19e9b5
Create Date: 2019-07-26 14:00:49.385674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'eac00fc6a70d'
down_revision = 'c6aead19e9b5'
branch_labels = None
depends_on = None

naming_convention = {
    "fk":
    "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    with op.batch_alter_table('product', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_product_file_id_file', type_='foreignkey')
        batch_op.drop_index('ix_product_type')

    op.rename_table('product', 'product_old')
    op.rename_table('file', 'product')
    op.rename_table('product_old', 'file')

    with op.batch_alter_table('file') as batch_op:
        batch_op.alter_column('file_id', nullable=True, new_column_name='product_id')

    with op.batch_alter_table('product') as batch_op:
        batch_op.create_index(batch_op.f('ix_product_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_type'), ['type'], unique=False)
        batch_op.drop_index('ix_file_channel')
        batch_op.drop_index('ix_file_date')
        batch_op.drop_index('ix_file_name')
        batch_op.drop_index('ix_file_region')
        batch_op.drop_index('ix_file_source')
        batch_op.drop_index('ix_file_type')

    # I don't understand why, but this needs to be seperate
    with op.batch_alter_table('file') as batch_op:
        batch_op.create_foreign_key('file_product', 'product', ['product_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_file_path'), ['path'], unique=True)
        batch_op.create_index(batch_op.f('ix_file_size'), ['size'], unique=False
)
        batch_op.create_index(batch_op.f('ix_file_type'), ['type'], unique=False
)
        batch_op.drop_index('ix_product_path')
        batch_op.drop_index('ix_product_size')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    with op.batch_alter_table('product') as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_type'))

    with op.batch_alter_table('file') as batch_op:
        batch_op.drop_constraint('file_product', type_='foreignkey')
        batch_op.create_index('ix_product_type', ['type'], unique=False)
        batch_op.create_index('ix_product_size', ['size'], unique=False)
        batch_op.create_index('ix_product_path', ['path'], unique=1)
        batch_op.drop_index(batch_op.f('ix_file_type'))
        batch_op.drop_index(batch_op.f('ix_file_size'))
        batch_op.drop_index(batch_op.f('ix_file_path'))

    with op.batch_alter_table('product') as batch_op:
        batch_op.create_index('ix_file_type', ['type'], unique=False)
        batch_op.create_index('ix_file_source', ['source'], unique=False)
        batch_op.create_index('ix_file_region', ['region'], unique=False)
        batch_op.create_index('ix_file_name', ['name'], unique=False)
        batch_op.create_index('ix_file_date', ['date'], unique=False)
        batch_op.create_index('ix_file_channel', ['channel'], unique=False)
        batch_op.drop_index(batch_op.f('ix_product_source'))
        batch_op.drop_index(batch_op.f('ix_product_region'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_date'))
        batch_op.drop_index(batch_op.f('ix_product_channel'))

    op.rename_table('product', 'product_new')
    op.rename_table('file', 'product')
    op.rename_table('product_new', 'file')

    with op.batch_alter_table('product') as batch_op:
        batch_op.alter_column('product_id', nullable=True, new_column_name='file_id')

    # ... likewise ...
    with op.batch_alter_table('product', naming_convention=naming_convention) as batch_op:
        batch_op.create_foreign_key('fk_product_file_id_file', 'file', ['file_id'], ['id'])


