"""added index to help out filters

Revision ID: f6a034af334b
Revises: 8b4c2c0c2365
Create Date: 2019-11-29 09:06:25.783604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a034af334b'
down_revision = '8b4c2c0c2365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_filter', ['type', 'source', 'region', 'channel', 'style', 'nnn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_filter')

    # ### end Alembic commands ###
